### ISSUE TITLE
Add Range support

### ISSUE THREAD

**Issue by lnicola** [Ekranos/rocket_static_fs#1]
Basically, what the title says. For larger files, `Range` is pretty much a must.

**Comment by Ekranos** [comment]
Yeah, `Range` is a must. I totally forgot about it since I just had my usual small assets use case.

I guess this will be the next thing that will be done. But for that I need to clean everything up or it will get super messy.

**Comment by lnicola** [comment]
Unrelated: your computer clock might be a bit wrong :smile:.

**Comment by Ekranos** [comment]
Yeah, I am at work and we have lot's of outgoing ports blocked, so NTP doesn't work. And since I am dual-booting Windows and Linux and both read/write the system clock slightly different, I sometimes have wrong system times when I forget to manually set it. ¯\_(ツ)_/¯

**Comment by Ekranos** [comment]
I will play with this a little bit more, but it should work. Since I never really implemented anything like that I could be wrong though. If this proves to be correctly implemented, then I will publish it as version 2.0 since the API changed as well cause of a further abstraction over the filesystem for future in-binary asset support.

**Comment by lnicola** [comment]
I can't test it, but two things:

- `Range` can have multiple spans, you're only using one
- maybe I misread your code, but have you seen [this](https://doc.rust-lang.org/std/io/trait.Read.html#method.take)?

**Comment by Ekranos** [comment]
I have looked for something like std::io::Read#take but I searched for range, limit and stuff, but never thought about take. Sometimes Rust is more Rubyish than I think :+1: 

I have seen the multipart range, but it is "totally different" from a single range, by requiring a multipart response which is no priority to be honest. I researched a bit and at least download continuations pretty much always use a single range. I can't really think of a real use case for multipart ranges, do you have one or a few. Maybe it is more important than I think it is.

I mean if you really need it, feel free to open a PR. The next thing I will do is most probably the asset embedding support.

**Comment by lnicola** [comment]
> I searched for range, limit and stuff, but never thought about take

Just like the `Iterator` method. And yes, I only recently found about it.

> I can't really think of a real use case for multipart ranges, do you have one or a few.

No, I'm totally fine with the fallback. I would have complained if it did something else, like sending only the first part :smile:. HTTP is complicated.
